### PR TITLE
Generate with string.

### PR DESCRIPTION
**Pull request by codingPrimate**
Also correctly link in the `readme` file.

### CODE REVIEW

**Comment by orignal** [comment]
You should not call i2p::data::PrivateKeys tmp_key = i2p::data::PrivateKeys::CreateRandomKeys (type) on every iteration but change padding only. ElGamal keys are expesive

**Comment by codingPrimate** [comment]
Okey...

**Comment by majestrate** [comment]
suggestion, write another tool for vanity addresses and make a new PR.

**Comment by codingPrimate** [comment]
You have a good idea.

**Pull request closed without merging**
