### PR TITLE
Vanity stuff

### PR DESCRIPTION
**Pull request by SOUx4cx4fx56x69**

### CODE REVIEW

**Comment by SOUx4cx4fx56x69** [comment]
lock@lock:~/i2pd-tools/i2pd-tools$ time ./vain dat.dat zzznoob 7

**Comment by majestrate** [comment]
vanitygen.cpp:71:19: error: expected primary-expression before ‘__attribute__’

**Comment by SOUx4cx4fx56x69** [comment]
hm

**Comment by SOUx4cx4fx56x69** [comment]
Oops-oops. lol

**Pull request merged**
